.github/workflows/build.yml
.github/workflows/release.yml

Required by newest rolout version

[ci] Bump node version used by GHA

---

README.md
src/minimalistic-area-card.ts

Closes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/39.

[feature] conditionally hide entity by state value.

---

README.md
src/minimalistic-area-card.ts

Now we can use templates in `${...}`.

[Feature] Add Experimental support for templating

---

README.md
src/minimalistic-area-card.ts

Add more variables into templates to simplify templates.

[experimental] Expose more variables into templates

---

README.md

[hotfix] Update example in README

---

src/minimalistic-area-card.ts

We don't need to update the list of tracked entities in every single update loop. I also fixed some JS errors during the config edit.

[fix] refresh entity list just when config changed

---

README.md
src/minimalistic-area-card.ts

Closes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/58

[Feature] Allow to specify the section for entity

---

README.md
src/minimalistic-area-card.ts

This cleanup allows to use defined order and simplifies code.

[cleanup] Force dialog and handle all button in the same way.

---

README.md
src/minimalistic-area-card.ts
src/types.ts

This allows to set text-align to left,right or center for title, sensors and buttons. Default values stays same.

[feature] Allow to speficy text alignment

---

README.md
src/minimalistic-area-card.ts
src/types.ts

Added new section for entitties - title - displayed in the same area as title.

[experimental] Introduce title entities and entity_type

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/question.yml

[GH] Update issue templates

---

src/minimalistic-area-card.ts

[cleanup] Some code cleanup to improve maintainability

---

.github/workflows/build.yml
.github/workflows/release.yml
.gitignore
jest.config.js
package.json
test/simple.test.ts
tsconfig.json
yarn.lock

Adding Jest as test framework.

Introduce test framework

---

README.md
src/minimalistic-area-card.ts
src/types.ts
src/utils.ts
test/utils.test.ts

Small cleanup in templates, added tests and return is now optional.

Templates now don't require to use return

---

src/minimalistic-area-card.ts
test/minimalistic-area-card.test.ts

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/175

[175] The card is not registered as custom card.

---

src/minimalistic-area-card.ts
src/types.ts
test/minimalistic-area-card.test.ts

[bugfix] Fix layout options to enable edit rows/columns from UI

---

README.md
src/minimalistic-area-card.ts
src/types.ts

Closes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/178

Use area icon and switch default value for show_area_icon to false

---

src/minimalistic-area-card.ts

Closes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/181

[181] Some icons are not visible in light mode

---

src/minimalistic-area-card.ts

Those z-index was not correct and image was not displayed. Also added missing border-radius - thanks @LiquidPT

[homeassistant-minimalistic-area-card-183] Image is not displayed

---

README.md

`darken_image` seemed to be misplaced under the entities. While I was fixing that, I looked at the config in code to see if there were others that should be moved

Update property documentation in the README

---

src/minimalistic-area-card.ts

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/204

[FIX-204] Allow to show entities without entity_id property

---

README.md
package.json
src/minimalistic-area-card.ts
src/types.ts
src/utils.ts
yarn.lock

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/195

[Feature] Allow to override color and background color for card.

---

README.md
src/minimalistic-area-card.ts
src/types.ts

Discussed in https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/216#issuecomment-2660137918

Support for more granular color settings

---

README.md

https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/128#issuecomment-2669617563

[README] Add YT link describing how to use this card.

---

README.md
src/minimalistic-area-card.ts

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/234

[feature] Allow to speficy the default value for force_dialog

---

src/minimalistic-area-card.ts

Align default icon and state color.

[FIX] The default state color should be --secondary-text-color

---

README.md
src/minimalistic-area-card.ts
src/types.ts
src/utils.ts
test/minimalistic-area-card.test.ts
test/utils.test.ts

Introduce unit_of_measurement param on entity level.
Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/241

[FR]: Allow to set unit_of_measurement on the entity level

---

src/minimalistic-area-card.ts

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/250

[bug] Fix state matching for entities

---

README.md
src/utils.ts
test/utils.test.ts

Fixes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/249.

[Feature] Introduce template helpers.

---

README.md
src/minimalistic-area-card.ts
src/types.ts
src/utils.ts
test/utils.test.ts

Closes https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/116.

[116] Fix misalignment for the icons in sensors area 

---

package.json
yarn.lock

Fix build issue in https://github.com/LesTR/homeassistant-minimalistic-area-card/pull/314

[hotfix] Add missing dev @babel/runtime

---

README.md

The last part of https://github.com/LesTR/homeassistant-minimalistic-area-card/issues/128.

[128] Add instalation info into readme
